### ISSUE TITLE
Entity attribute changes value type from spring bean to Expression for data load task

### ISSUE THREAD

**Issue by maistrenkoIulia** [Haulmont/jmix-bpm-public#68]
Jmix version: 1.1.0-SNAPSHOT
Jmix Studio plugin version: 1.1.SNAPSHOT3579-212
IntelliJ version: IntelliJ IDEA 2021.2.2 (Ultimate Edition)

TC: create entity with assotiation to user
run app
modeler>add data load task with type = create for Person entity
entity attrs>add>select user attr, 
value type from spring bean
set method, params
Ok
entity attrs>view user attr
ER: value type = spring bean
AR: value type = expression

relates to https://github.com/Haulmont/jmix-bpm-public/issues/27

**Comment by artemy63** [comment]
For QA:
1. In test project add into `application.properties` next row
```
jmix.bpm.dataTaskSpringBeanEntityAttributeEnabled = true
```
in order to enable specifying for attributes springBeans.
2. Open the BPM modeler
3. Add "Entity Data Task" with "Create entity" task type
4. For new entity for some attributes choose "Spring bean", specify method of bean and parametrs if necessary
5. Try to edit added attribute
ER: type of the attribute value should not shanged and equals to "Spring bean", method and parameters are there
6. Check that for "Direct value" and "Expression" types there are also no problems

**Comment by konyashkina** [comment]
Tested on
Jmix version: 1.3.999-SNAPSHOT
Jmix Studio plugin version: 1.3.SNAPSHOT4124-213
IntelliJ version: IntelliJ IDEA 2021.3.2 (Ultimate Edition)
